###list coin by symbol local
GET http://localhost:3000/coins/?filter=

###list coin by symbol docker
GET http://localhost:3002/coins/?filter=

###get coin value by symbol docker
GET http://localhost:3002/coins/add/:symbol
