version: '3.8'

services:

  user-api:
    build:
      context: ./dashboard-user-api
      dockerfile: Dockerfile
    env_file:
      - ./env/.env
    ports:
      - '3001:3000'
    depends_on:
      - mysql
    networks:
      - dashboard-network


  dashboard-api:
    build:
      context: ./dashboard-api
      dockerfile: Dockerfile
    env_file:
      - ./env/dashboard-api.env
    ports:
      - '3002:3000'
    depends_on:
      mongo:
        condition: service_started
      mssql:
        condition: service_started
    networks:
      - dashboard-network


  dashboard-spa:
    build:
      context: ./dashboard-spa
      dockerfile: Dockerfile
    env_file:
      - ./env/dashboard-spa.env
    ports:
      - '8081:80'
    depends_on:
      - dashboard-api
      - user-api
    volumes:
      - ./env/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - dashboard-network


  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SenhaDoRoot123
      # Mesmo que você já defina MYSQL_DATABASE, o script garantirá a criação e os privilégios.
      MYSQL_DATABASE: userclient
      MYSQL_USER: usrclient
      MYSQL_PASSWORD: SenhaDoUsuario123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dashboard-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express              # Define a edição como Express (gratuita)
    ports:
      - "14444:1433"                   # Mapeia a porta padrão do MSSQL para o host
    volumes:
      - mssql_data:/var/opt/mssql      # Volume para persistência dos dados
    networks:
      - dashboard-network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - dashboard-network


volumes:
  mysql_data:
  mssql_data:
  mongo_data:
networks:
  dashboard-network:
    driver: bridge