version: '3.8'

services:

  user:
    build:
      context: ./dashboard-user-api
      dockerfile: Dockerfile
    env_file:
      - ./env/.env
    ports:
      - '3001:3000'
    depends_on:
      - mysql

  dashboard-api:
    build:
      context: ./dashboard-api
      dockerfile: Dockerfile
    env_file:
      - ./env/dashboard-api.env/
    ports:
      - '3002:3000'
    depends_on:
      - mssql

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SenhaDoRoot123
      # Mesmo que você já defina MYSQL_DATABASE, o script garantirá a criação e os privilégios.
      MYSQL_DATABASE: userclient
      MYSQL_USER: usrclient
      MYSQL_PASSWORD: SenhaDoUsuario123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express              # Define a edição como Express (gratuita)
    ports:
      - "14444:1433"                   # Mapeia a porta padrão do MSSQL para o host
    volumes:
      - mssql_data:/var/opt/mssql      # Volume para persistência dos dados

volumes:
  mysql_data:
  mssql_data:
